---
title: "MY TITLE"
date: 2018-04-25
---

title: Test Site 
author: GitHub Userr
email: your-email@domainss.com
description: > # this means to ignore newlines until "baseurl:"
  Already wrote bla bla

# social links
twitter_username: tivitusername
github_username:  sercanerhan

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
